# Generated by Django 4.2.7 on 2024-05-14 13:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_product_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="CAD",
            field=models.BooleanField(
                default=False, verbose_name="CAD (Cash Against Document)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand_name",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Brand Name"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cert",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("BRC", "BRC Standard"),
                    ("COSMOS", "COSMOS Organic and Natural"),
                    ("CFC", "Cruelty Free Certificate"),
                    ("EnergyStar", "Energy Star"),
                    ("FairTradeCertificate", "Fair Trade Certificate"),
                    ("FCC", "FCC Certificate"),
                    ("FSC", "FSC Certificate"),
                    ("GOTS", "GOTS Certificcate"),
                    ("HACCP", "HACCP"),
                    ("HALAL", "HALAL Certificate"),
                    ("ISO9001", "ISO 9001"),
                    ("ISO14001", "ISO 14001"),
                    ("ISO22000", "ISO 22000"),
                    ("ISO_TS", "ISO_TS 16949"),
                    ("Kosher", "Kosher"),
                    ("Non-GMO", "Non-GMO Certificate"),
                    ("RoHS", "RoHS Compliance"),
                    ("Wrap", "Wrap Certificate"),
                    ("Other", "Other"),
                ],
                max_length=250,
                null=True,
                verbose_name="Certification Name",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cert_number",
            field=models.IntegerField(default=0, verbose_name="Certification Number"),
        ),
        migrations.AddField(
            model_name="product",
            name="cfr",
            field=models.BooleanField(default=False, verbose_name="CFR/CIF"),
        ),
        migrations.AddField(
            model_name="product",
            name="dap",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="date_valid",
            field=models.DateField(blank=True, help_text="format: Y-m-d", null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="ddp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="domestic_market",
            field=models.BooleanField(default=False, verbose_name="Domestic Market"),
        ),
        migrations.AddField(
            model_name="product",
            name="dpu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="exw",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="fas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="fca",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="fob",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="international_market",
            field=models.BooleanField(
                default=False, verbose_name="International Market"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="issue_date",
            field=models.DateField(blank=True, help_text="format: Y-m-d", null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="lc",
            field=models.BooleanField(
                default=False, verbose_name="L/C Letter of Credit"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="order_quantity",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Maximum Order Quantity",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="order_unit",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Kilogram", "Kilogram"),
                    ("Litre", "Litre"),
                    ("Pack", "Pack"),
                    ("Set", "Set"),
                    ("Ton", "Ton"),
                ],
                max_length=250,
                null=True,
                verbose_name="Measure",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="organization",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="papss",
            field=models.BooleanField(default=False, verbose_name="PAPSS"),
        ),
        migrations.AddField(
            model_name="product",
            name="peoples_pay",
            field=models.BooleanField(default=False, verbose_name="Peoples Pay"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_cap",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Product Capacity"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sample_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default="0.00",
                max_digits=20,
                null=True,
                verbose_name="Sample Price",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="time_span",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly"),
                    ("Bi-Yearly", "Bi-Yearly"),
                    ("Yearly", "Yearly"),
                ],
                max_length=250,
                null=True,
                verbose_name="Time Span",
            ),
        ),
    ]
