# Generated by Django 4.2.7 on 2024-06-13 11:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_cad_product_brand_name_product_cert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='CAD',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cfr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dap',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ddp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='domestic_market',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dpu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='exw',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fas',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fca',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fob',
        ),
        migrations.RemoveField(
            model_name='product',
            name='international_market',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='papss',
        ),
        migrations.RemoveField(
            model_name='product',
            name='peoples_pay',
        ),
        migrations.AddField(
            model_name='product',
            name='market_type',
            field=models.CharField(blank=True, choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=250, null=True, verbose_name='Trading Areas'),
        ),
        migrations.AddField(
            model_name='product',
            name='paymentS',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('papss', 'PAPSS'), ('peoples_pay', 'Peoples Pay'), ('letter_of_credit', 'Letter of Credit'), ('cash_against_document', 'Cash Against Document')], max_length=250, null=True, verbose_name='Payment Methods'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.CharField(blank=True, choices=[('ESX', 'ESX'), ('FCA', 'FCA'), ('FAS', 'FAS'), ('FOB', 'FOB'), ('CFR/CIF', 'CFR/CIF'), ('DPU', 'DPU'), ('DPA', 'DPA'), ('DDP', 'DDP')], max_length=250, null=True, verbose_name='Shipping Information'),
        ),
    ]
