# Generated by Django 4.2.7 on 2024-06-18 14:22

import apps.inventory.models
import django.core.validators
from django.db import migrations, models
import django_measurement.models
import measurement.measures.volume


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_brand_name_product_cert_product_cert_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Product Name')),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=apps.inventory.models.current_year, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2024)], verbose_name='Production Year')),
                ('specs', models.TextField(blank=True, max_length=250, null=True, verbose_name='Product Specifications')),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='Message To Buyer')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=20, null=True, verbose_name='Price Offer')),
                ('unit', django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume, verbose_name='Unit')),
                ('quotation_image', models.FileField(blank=True, null=True, upload_to=apps.inventory.models.QuotationForm.user_directory_path, verbose_name='Upload pictures of product')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=apps.inventory.models.QuotationImage.user_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='order_unit',
            field=django_measurement.models.MeasurementField(blank=True, max_length=250, measurement=measurement.measures.volume.Volume, null=True, verbose_name='Measure'),
        ),
        migrations.AlterField(
            model_name='sourcingrequest',
            name='unit',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.volume.Volume, null=True),
        ),
    ]
