# Generated by Django 4.2.7 on 2024-06-21 11:43

import apps.inventory.models
import django.core.validators
from django.db import migrations, models
import django_measurement.models
import measurement.measures.volume


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_brand_name_product_cert_product_cert_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcingrequest',
            name='unit',
            field=django_measurement.models.MeasurementField(default='1.0', measurement=measurement.measures.volume.Volume),
        ),
    ]
