# Generated by Django 4.2.7 on 2024-05-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_product_cad_product_brand_name_product_cert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="time_span",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly"),
                    ("Bi-Yearly", "Bi-Yearly"),
                    ("Yearly", "Yearly"),
                ],
                max_length=250,
                null=True,
                verbose_name="Time Span",
            ),
        ),
    ]
