# Generated by Django 4.2.7 on 2024-06-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_quotationform_quotationimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_unit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='quotationform',
            name='unit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sourcingrequest',
            name='unit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
