# Generated by Django 4.2.7 on 2024-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_alter_product_cert_alter_product_order_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("papss", models.BooleanField(default=False, verbose_name="PAPSS")),
                (
                    "peoples_pay",
                    models.BooleanField(default=False, verbose_name="Peoples Pay"),
                ),
                (
                    "lc",
                    models.BooleanField(
                        default=False, verbose_name="L/C Letter of Credit"
                    ),
                ),
                (
                    "CAD",
                    models.BooleanField(
                        default=False, verbose_name="CAD (Cash Against Document)"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="CAD",
        ),
        migrations.RemoveField(
            model_name="product",
            name="lc",
        ),
        migrations.RemoveField(
            model_name="product",
            name="papss",
        ),
        migrations.RemoveField(
            model_name="product",
            name="peoples_pay",
        ),
    ]
