# Generated by Django 4.2.7 on 2024-06-27 12:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_order_unit_alter_quotationform_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENTMETHODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TradingAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='paymentS',
            new_name='payments',
        ),
        migrations.AlterField(
            model_name='product',
            name='cert',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BRC', 'BRC Standard'), ('COSMOS', 'COSMOS Organic and Natural'), ('CFC', 'Cruelty Free Certificate'), ('EnergyStar', 'Energy Star'), ('FairTradeCertificate', 'Fair Trade Certificate'), ('FCC', 'FCC Certificate'), ('FSC', 'FSC Certificate'), ('GOTS', 'GOTS Certificcate'), ('HACCP', 'HACCP'), ('HALAL', 'HALAL Certificate'), ('ISO9001', 'ISO 9001'), ('ISO14001', 'ISO 14001'), ('ISO22000', 'ISO 22000'), ('ISO_TS', 'ISO_TS 16949'), ('Kosher', 'Kosher'), ('Non-GMO', 'Non-GMO Certificate'), ('RoHS', 'RoHS Compliance'), ('Wrap', 'Wrap Certificate'), ('Other', 'Other')], max_length=250, null=True, verbose_name='Certification Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='market_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=250, null=True, verbose_name='Trading Areas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ESX', 'ESX'), ('FCA', 'FCA'), ('FAS', 'FAS'), ('FOB', 'FOB'), ('CFR/CIF', 'CFR/CIF'), ('DPU', 'DPU'), ('DPA', 'DPA'), ('DDP', 'DDP')], max_length=250, null=True, verbose_name='Shipping Information'),
        ),
        migrations.AlterField(
            model_name='sourcingrequest',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Name'),
        ),
    ]
