# Generated by Django 4.2.7 on 2024-05-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0010_paymentmethods_remove_product_cad_remove_product_lc_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentMethods",
        ),
        migrations.AddField(
            model_name="product",
            name="CAD",
            field=models.BooleanField(
                default=False, verbose_name="CAD (Cash Against Document)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="lc",
            field=models.BooleanField(
                default=False, verbose_name="L/C Letter of Credit"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="papss",
            field=models.BooleanField(default=False, verbose_name="PAPSS"),
        ),
        migrations.AddField(
            model_name="product",
            name="peoples_pay",
            field=models.BooleanField(default=False, verbose_name="Peoples Pay"),
        ),
    ]
